#!/bin/bash
# GEMM search v3 on the RTX 6000 Ada (basal-1.5-4.5B): v3 table generated by this build, timing against the v2 table
# (same binary, rotating order, locked clock), batch invariance with v3, decision set against FP32 with v2 and v3
cd /work
export BASAL_NO_UPDATE_CHECK=1
B=target/release/basal
M=/work/.models/basal-1.5-4.5B; REF=reports/reference-basal-1.5-4.5B-fp32; R=out/refs/reference-basal-1.5-4.5B-fp32
O=out/gemm3-ada; mkdir -p $O/4.5B
cp out/prof/gemm/basal-1.5-4.5B-f16.json $O/table-v2.json
t0=$(date +%s)
$B --color never gemm-search --model $M --invariant --out $O/table-v3.json > $O/gemm-search.log 2>&1
echo "v3 table: $(( $(date +%s) - t0 )) s" | tee $O/table-times.txt
nvidia-smi --query-gpu=timestamp,temperature.gpu,clocks.sm,power.draw --format=csv,noheader -l 1 > $O/clocks.csv &
SMI=$!
for rep in 1 2 3 4; do
  order="v2 v3"; [ $((rep % 2)) = 0 ] && order="v3 v2"
  for v in $order; do
    $B --color never bench --model $M --gemm-table $O/table-$v.json --reference $REF --out $O/4.5B/bench-$v-$rep.json > /dev/null 2>&1
    $B --color never bench-requests --model $M --gemm-table $O/table-$v.json --requests out/prof/ladder-full/requests.jsonl \
      --reps 2 --out $O/4.5B/requests-$v-$rep.json > /dev/null 2>&1
  done
done
kill $SMI
echo "=== invariance $(date +%T)"
for b in single tree budget; do
  $B --color never export --model $M --gemm-table $O/table-v3.json --batching $b --inputs $REF --out $O/export-$b > /dev/null 2>&1
done
for b in tree budget; do printf "%-24s " "single-vs-$b"; $B compare --a $O/export-single --b $O/export-$b --out $O/compare-single-vs-$b.json | tail -1; done
echo "=== decision set $(date +%T)"
for v in v2 v3; do
  $B --color never export --model $M --gemm-table $O/table-$v.json --batching tree --inputs $R --out $O/export-ds-$v > /dev/null 2>&1
  printf "%-24s " "ds-fp32-vs-$v"; $B compare --a $R --b $O/export-ds-$v --out $O/compare-ds-fp32-vs-$v.json | tail -1
done
echo DONE
