#!/bin/bash
# Check of a change of the batch-invariant GEMM search on one rented GPU (tools/cloud/basal-cloud.py), for the models
# GEMM_MODELS (default "4.5B"):
#   - tables: the installed release (old search, BASAL_HOME=/data/old) and this build (new search), generation time
#   - time: context ladder up to 16k tokens and basal-bench, with the old table, the new table and the cuBLASLt
#     heuristic, GEMM_REPS repetitions (default 3) in rotating order with the SM clock locked when allowed
#   - batch invariance with the new table: exports single / tree / budget of the 44 basal-bench items, compared (0.0)
#   - agreement with upstream FP32 on the decision set (tools/decision-sets) with the old and the new table
# Run in /work after `push` and `sync tools/bench tools/perf reports/reference-basal-1.5-4.5B-fp32
# reports/reference-1.5-max-fp32 .cache/cloud/refs .cache/decision-sets/set.jsonl`. Writes out/gemm/.
set -e
cd /work
export HF_HOME=/data/hf BASAL_NO_UPDATE_CHECK=1
O=out/gemm
mkdir -p $O
nvidia-smi --query-gpu=name,driver_version,compute_cap,power.limit --format=csv,noheader > $O/gpu.txt
up() {
  for _ in $(seq 3600); do
    curl --fail-with-body --silent "http://127.0.0.1:$1/health" > /dev/null && return 0
    pgrep -f "$2" > /dev/null || return 1
    sleep 1
  done
  return 1
}
snap() { echo /data/hf/hub/models--Remek--$1/snapshots/$2; }
declare -A REV=([4.5B]=784a683bfadcc8865238fc0fc74a83b4000269bc [max]=be1b5ee7e7a9755a931262fa7fab4f59be0fd03c
                [mini]=1978d0705ce09cd2d7d8d3e87b304468121e7255)
declare -A REF=([4.5B]=reports/reference-basal-1.5-4.5B-fp32 [max]=reports/reference-1.5-max-fp32)
OLD=/opt/basal-release/libexec/basal/basal-cuda
for s in ${GEMM_MODELS:-4.5B}; do
  m=basal-1.5-$s; dir=$(snap $m ${REV[$s]})
  L=$O/ladder-$s
  (cd tools/bench && python3 make_context_ladder.py --model $m --out /work/$L --sizes 512 1792 2048 4096 8192 16384)
  # tables: old search (release binary) and new search (this build), each generated by `serve` (gemm_table: auto)
  for v in old new; do
    if [ $v = old ]; then H=/data/old; BIN="env LD_LIBRARY_PATH=/data/basal/.local/cuda/12.9.1/lib $OLD"; else H=/data/basal; BIN=basal-dev; fi
    t0=$(date +%s)
    BASAL_HOME=$H $BIN --color never serve --model $dir --addr 127.0.0.1:8100 > $O/serve-$s-$v.log 2>&1 &
    up 8100 "[c]olor never serve" || true
    echo "$s $v table: $(( $(date +%s) - t0 )) s" >> $O/table-times.txt
    pkill -INT -f "[c]olor never serve" || true; sleep 5
  done
  TOLD=/data/old/.cache/gemm/$m-f16.json; TNEW=/data/basal/.cache/gemm/$m-f16.json
  cp $TOLD $O/table-$s-old.json; cp $TNEW $O/table-$s-new.json
  export BASAL_HOME=/data/basal
  echo "=== $s timing $(date +%H:%M:%S)"
  MAXC=$(nvidia-smi --query-gpu=clocks.max.sm --format=csv,noheader,nounits | head -1)
  sudo -n nvidia-smi -lgc $((MAXC * 8 / 10)),$((MAXC * 8 / 10)) > $O/lock.txt 2>&1 || true
  nvidia-smi --query-gpu=timestamp,temperature.gpu,clocks.sm,power.draw --format=csv,noheader -l 1 > $O/clocks-$s.csv &
  SMI=$!
  mkdir -p $O/$s
  for rep in $(seq ${GEMM_REPS:-3}); do
    order="old new heuristic"; [ $((rep % 2)) = 0 ] && order="heuristic new old"
    for v in $order; do
      G="--gemm-table $O/table-$s-$v.json"; [ $v = heuristic ] && G=""
      basal-dev --color never bench-requests --model $dir $G --requests $L/requests.jsonl --reps 2 \
        --out $O/$s/requests-$v-$rep.json > /dev/null 2>&1
      basal-dev --color never bench --model $dir $G --reference ${REF[$s]} --out $O/$s/bench-$v-$rep.json > /dev/null 2>&1
    done
  done
  kill $SMI
  sudo -n nvidia-smi -rgc > /dev/null 2>&1 || true
  echo "=== $s invariance $(date +%H:%M:%S)"
  for b in single tree budget; do
    basal-dev --color never export --model $dir --gemm-table $TNEW --batching $b --inputs ${REF[$s]} \
      --out $O/export-$s-$b > /dev/null 2>&1
  done
  for b in tree budget; do
    printf "%-32s " "single-vs-$b-$s"; basal-dev --color never compare --a $O/export-$s-single --b $O/export-$s-$b \
      --out $O/compare-single-vs-$b-$s.json | tail -1
  done
  printf "%-32s " "fp32-vs-new-$s"; basal-dev --color never compare --a ${REF[$s]} --b $O/export-$s-tree \
    --out $O/compare-fp32-vs-new-$s.json | tail -1
  R=.cache/cloud/refs/reference-$m-fp32
  if [ -d $R ]; then
    echo "=== $s decision set $(date +%H:%M:%S)"
    for v in old new; do
      basal-dev --color never export --model $dir --gemm-table $O/table-$s-$v.json --batching tree --inputs $R \
        --out $O/export-$s-ds-$v > /dev/null 2>&1
      printf "%-32s " "decision-set-fp32-vs-$v-$s"; basal-dev --color never compare --a $R --b $O/export-$s-ds-$v \
        --out $O/compare-ds-fp32-vs-$v-$s.json | tail -1
    done
  fi
done
echo DONE
