#!/bin/bash
# A/B of two CUDA builds on one rented GPU (tools/cloud/basal-cloud.py), /opt/basal-dev/basal-cuda-base (A) and the
# pushed working tree basal-dev (B), for the models FWD_MODELS (default "4.5B max"):
#   - results: exports of the 44 basal-bench items (tree batching) by A and B compared (0.0 expected)
#   - time: `basal bench` (single decision) and the context ladder (`basal bench-requests`), REPS repetitions in
#     alternating order (A B B A ...), with the SM clock locked (nvidia-smi -lgc, when allowed) and logged
# Profiles of a build: tools/perf/run-profile-cloud.sh (after this script, on the same machine).
# GEMM tables: the built-in ones of this GPU (crates/basal-cli/gemm-tables), else generated by B.
# Run in /work after pushing both binaries and `sync tools/bench tools/perf crates/basal-cli/gemm-tables
# reports/reference-basal-1.5-4.5B-fp32 reports/reference-1.5-max-fp32`. Writes out/fwd/.
cd /work
export HF_HOME=/data/hf BASAL_HOME=/data/basal BASAL_NO_UPDATE_CHECK=1
LIBS=/data/basal/.local/cuda/12.9.1/lib
[ -d /usr/local/cuda-12.9/compat ] && LIBS=/usr/local/cuda-12.9/compat:$LIBS
O=out/fwd
mkdir -p $O
nvidia-smi --query-gpu=name,driver_version,compute_cap,power.limit,clocks.max.sm --format=csv,noheader > $O/gpu.txt
GPU=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
run() {  # run A|B ARGS...
  local v=$1; shift
  case $v in
    A) LD_LIBRARY_PATH=$LIBS /opt/basal-dev/basal-cuda-base --color never "$@" ;;
    B) basal-dev --color never "$@" ;;
  esac
}
snap() { echo /data/hf/hub/models--Remek--$1/snapshots/$2; }
declare -A REV=([4.5B]=784a683bfadcc8865238fc0fc74a83b4000269bc [max]=be1b5ee7e7a9755a931262fa7fab4f59be0fd03c)
declare -A REF=([4.5B]=reports/reference-basal-1.5-4.5B-fp32 [max]=reports/reference-1.5-max-fp32)
slug=$(echo "$GPU" | tr 'A-Z' 'a-z' | tr -cs 'a-z0-9' '-' | sed 's/-$//')
for s in ${FWD_MODELS:-4.5B max}; do
  m=basal-1.5-$s; dir=$(snap $m ${REV[$s]})
  (cd tools/bench && python3 make_context_ladder.py --model $m --out /work/$O/ladder-$s > /dev/null)
  T=crates/basal-cli/gemm-tables/$slug--$m--f16--cublaslt120901.json
  if [ ! -f $T ]; then
    T=$O/table-$s.json
    [ -f $T ] || run B gemm-search --model $dir --invariant --out $T > $O/gemm-$s.log 2>&1
  fi
  echo "$s table: $T" >> $O/tables.txt
  echo "=== $s results $(date +%T)"
  for v in A B; do
    run $v export --model $dir --gemm-table $T --batching tree --inputs ${REF[$s]} --out $O/export-$s-$v > /dev/null 2>&1
  done
  printf "%-12s " "$s A vs B"; run B compare --a $O/export-$s-A --b $O/export-$s-B --out $O/compare-$s-A-B.json | tail -1
done

# time, clock locked at 80% of the maximum SM clock (below the power limit's throttling) when the driver allows it
MAXC=$(nvidia-smi --query-gpu=clocks.max.sm --format=csv,noheader,nounits | head -1)
sudo -n nvidia-smi -lgc $((MAXC * 8 / 10)),$((MAXC * 8 / 10)) > $O/lock.txt 2>&1 || true
nvidia-smi --query-gpu=timestamp,temperature.gpu,clocks.sm,power.draw --format=csv,noheader -l 1 > $O/clocks.csv &
SMI=$!
for s in ${FWD_MODELS:-4.5B max}; do
  m=basal-1.5-$s; dir=$(snap $m ${REV[$s]}); T=$(awk -v s="$s" '$1 == s {print $3}' $O/tables.txt)
  echo "=== $s time $(date +%T)"
  mkdir -p $O/$s
  for rep in $(seq ${REPS:-4}); do
    order="A B"; [ $((rep % 2)) = 0 ] && order="B A"
    for v in $order; do
      echo "$(date +%T) $s rep $rep $v" >> $O/order.txt
      run $v bench --model $dir --gemm-table $T --reference ${REF[$s]} --out $O/$s/bench-$v-$rep.json > /dev/null 2>&1
      run $v bench-requests --model $dir --gemm-table $T --requests $O/ladder-$s/requests.jsonl --reps 2 \
        --out $O/$s/requests-$v-$rep.json > /dev/null 2>&1
    done
  done
done
kill $SMI
sudo -n nvidia-smi -rgc > /dev/null 2>&1 || true

echo DONE
