#!/bin/bash
# A/B of two CUDA builds on one rented GPU (tools/cloud/basal-cloud.py): /opt/basal-dev/basal-cuda-base (A) and the
# pushed working tree basal-dev (B), plus B with BASAL_ATT=tc-pipe (B+pipe), for the models AB_MODELS (default
# "4.5B max"), with one batch-invariant GEMM table per model (generated by B):
#   - results: exports of the 44 basal-bench items (tree batching) by A, B and B+pipe compared with each other
#   - time: `basal bench` (single decision) and the context ladder 512-16384 tokens (`basal bench-requests`)
# Run in /work after pushing both binaries and `sync tools/bench tools/perf reports/reference-basal-1.5-4.5B-fp32
# reports/reference-1.5-max-fp32`. Writes out/ab/.
set -e
cd /work
export HF_HOME=/data/hf BASAL_HOME=/data/basal BASAL_NO_UPDATE_CHECK=1
LIBS=/data/basal/.local/cuda/12.9.1/lib
[ -d /usr/local/cuda-12.9/compat ] && LIBS=/usr/local/cuda-12.9/compat:$LIBS
O=out/ab
mkdir -p $O
nvidia-smi --query-gpu=name,driver_version,compute_cap,power.limit --format=csv,noheader > $O/gpu.txt
run() {  # run VARIANT ARGS...: A, B or Bpipe
  local v=$1; shift
  case $v in
    A) LD_LIBRARY_PATH=$LIBS /opt/basal-dev/basal-cuda-base --color never "$@" ;;
    B) basal-dev --color never "$@" ;;
    Bpipe) BASAL_ATT=tc-pipe basal-dev --color never "$@" ;;
  esac
}
up() {
  for _ in $(seq 3600); do
    curl --fail-with-body --silent "http://127.0.0.1:$1/health" > /dev/null && return 0
    pgrep -f "[c]olor never serve" > /dev/null || return 1
    sleep 1
  done
  return 1
}
snap() { echo /data/hf/hub/models--Remek--$1/snapshots/$2; }
declare -A REV=([4.5B]=784a683bfadcc8865238fc0fc74a83b4000269bc [max]=be1b5ee7e7a9755a931262fa7fab4f59be0fd03c)
declare -A REF=([4.5B]=reports/reference-basal-1.5-4.5B-fp32 [max]=reports/reference-1.5-max-fp32)
for s in ${AB_MODELS:-4.5B max}; do
  m=basal-1.5-$s; dir=$(snap $m ${REV[$s]})
  L=$O/ladder-$s
  (cd tools/bench && python3 make_context_ladder.py --model $m --out /work/$L)
  T=/data/basal/.cache/gemm/$m-f16.json
  if [ ! -f $T ]; then
    t0=$(date +%s)
    basal-dev --color never serve --model $dir --addr 127.0.0.1:8100 > $O/serve-$s.log 2>&1 &
    up 8100 || true
    echo "$s table: $(( $(date +%s) - t0 )) s" >> $O/table-times.txt
    pkill -INT -f "[c]olor never serve" || true; sleep 5
  fi
  cp $T $O/table-$s.json
  echo "=== $s results $(date +%H:%M:%S)"
  for v in A B Bpipe; do
    run $v export --model $dir --gemm-table $T --batching tree --inputs ${REF[$s]} --out $O/export-$s-$v > /dev/null 2>&1
  done
  for pair in A:B B:Bpipe; do
    a=${pair%%:*}; b=${pair#*:}
    printf "%-22s " "$s $a vs $b"; run B compare --a $O/export-$s-$a --b $O/export-$s-$b --out $O/compare-$s-$a-$b.json | tail -1
  done
  printf "%-22s " "$s fp32 vs B"; run B compare --a ${REF[$s]} --b $O/export-$s-B --out $O/compare-$s-fp32-B.json | tail -1
  echo "=== $s time $(date +%H:%M:%S)"
  for v in A B Bpipe; do
    run $v bench --model $dir --gemm-table $T --reference ${REF[$s]} --out $O/bench-$s-$v.json > /dev/null 2>&1
    run $v bench-requests --model $dir --gemm-table $T --requests $L/requests.jsonl --reps 3 \
      --out $O/requests-$s-$v.json > /dev/null 2>&1
  done
done
echo DONE
