//! `basal gemm-share`: send the batch-invariant GEMM tables this machine generated (`gemm_table: auto`) to the
//! basal-rs project as GitHub issues, so that a later build ships them and other users of the same GPU skip the
//! search. Shows what would be sent and asks first (`--yes` skips the question, `--dry-run` only writes the issue
//! text). With an authenticated `gh` CLI the
//! issue is created directly; otherwise the issue text is written next to the table with the link of the issue form.
//!
//! A table holds the GPU name, the cuBLASLt version, the model and dtype, opaque cuBLASLt algorithm configurations and
//! their timings; the issue adds `basal --version` and the driver version. Nothing identifies the machine.

use std::io::{BufRead, IsTerminal, Write};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::Value;

use crate::config;

const REPO: &str = "itsoltech/basal-rs";
const LABEL: &str = "gemm-table";

/// A generated table of the cache that no table of this build matches.
struct Candidate {
    path: PathBuf,
    v: Value,
}

fn candidates(dir: &Path) -> Result<Vec<Candidate>> {
    let mut out = Vec::new();
    let Ok(rd) = std::fs::read_dir(dir) else { return Ok(out) };
    let bundled: Vec<Value> =
        config::bundled::TABLES.iter().filter_map(|(_, t)| serde_json::from_str::<Value>(t).ok()).collect();
    let mut paths: Vec<PathBuf> =
        rd.filter_map(|e| e.ok().map(|e| e.path())).filter(|p| p.extension().is_some_and(|x| x == "json")).collect();
    paths.sort();
    for path in paths {
        let Ok(v) = serde_json::from_str::<Value>(&std::fs::read_to_string(&path)?) else { continue };
        if v["invariant"].as_bool() != Some(true) || v["entries"].as_array().is_none_or(|e| e.is_empty()) {
            continue;
        }
        // tables of this build, or of an earlier one, for the same GPU, cuBLASLt and shapes need no sharing
        let same = |b: &Value| {
            b["gpu"] == v["gpu"]
                && b["cublaslt_version"] == v["cublaslt_version"]
                && b["dtype"] == v["dtype"]
                && b["shapes"] == v["shapes"]
                && b["gemm_search_version"].as_u64() >= v["gemm_search_version"].as_u64()
        };
        if bundled.iter().any(same) {
            continue;
        }
        out.push(Candidate { path, v });
    }
    Ok(out)
}

/// `nvidia-smi` driver version and compute capability, when available.
fn driver() -> Option<String> {
    let o = std::process::Command::new("nvidia-smi")
        .args(["--query-gpu=name,driver_version,compute_cap", "--format=csv,noheader"])
        .output()
        .ok()?;
    o.status.success().then(|| String::from_utf8_lossy(&o.stdout).lines().next().unwrap_or("").trim().to_string())
}

fn title(v: &Value) -> String {
    format!(
        "GEMM table: {}, {} ({}, cuBLASLt {})",
        v["gpu"].as_str().unwrap_or("?"),
        v["model"].as_str().unwrap_or("model ?"),
        v["dtype"].as_str().unwrap_or("?"),
        v["cublaslt_version"]
    )
}

fn body(v: &Value, drv: Option<&str>) -> Result<String> {
    let entries = v["entries"].as_array().map_or(0, |e| e.len());
    let slow: Vec<f64> = v["entries"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|e| Some(e["ms"].as_f64()? / e["best_candidate_ms"].as_f64()?))
        .collect();
    let mean = slow.iter().sum::<f64>() / slow.len().max(1) as f64;
    Ok(format!(
        "Batch-invariant GEMM table generated by `basal serve` (`gemm_table: auto`), sent with `basal gemm-share`.\n\n\
         | | |\n|---|---|\n| GPU | {} |\n| driver, compute capability | {} |\n| cuBLASLt | {} |\n| model, dtype | {}, {} |\n\
         | search version | {} |\n| made by | basal {} |\n| this machine's basal | {} ({}) |\n| entries | {entries} |\n\
         | mean time / fastest candidate per class | {mean:.3} |\n\n\
         Maintainers: check it on this GPU and cuBLASLt version (CONTRIBUTING.md, \"GEMM tables\"), then add it to \
         `crates/basal-cli/gemm-tables/`.\n\n```json\n{}\n```\n",
        v["gpu"].as_str().unwrap_or("?"),
        drv.unwrap_or("unknown"),
        v["cublaslt_version"],
        v["model"].as_str().unwrap_or("?"),
        v["dtype"].as_str().unwrap_or("?"),
        v["gemm_search_version"],
        v["basal"].as_str().unwrap_or("?"),
        env!("CARGO_PKG_VERSION"),
        env!("BASAL_GIT_SHA"),
        serde_json::to_string(v)?
    ))
}

fn gh_ready() -> bool {
    std::process::Command::new("gh")
        .args(["auth", "status"])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

pub fn run(dir: Option<PathBuf>, yes: bool, dry_run: bool) -> Result<()> {
    let dir = dir.unwrap_or_else(config::default_gemm_cache);
    let cands = candidates(&dir)?;
    if cands.is_empty() {
        crate::note!(
            "no GEMM tables to share in {}: none generated here, or this build already has them",
            crate::term::P(&dir)
        );
        return Ok(());
    }
    let drv = driver();
    crate::note!("tables generated on this machine that basal {} does not ship:", env!("CARGO_PKG_VERSION"));
    for c in &cands {
        crate::note!("  {} ({})", title(&c.v), crate::term::P(&c.path));
    }
    crate::note!(
        "each becomes a public issue in github.com/{REPO}: GPU, driver version, cuBLASLt version, model, the table's \
         cuBLASLt configurations and timings; nothing that identifies this machine"
    );
    if dry_run {
        for c in &cands {
            let file = c.path.with_extension("issue.md");
            std::fs::write(&file, body(&c.v, drv.as_deref())?)
                .with_context(|| format!("writing {}", file.display()))?;
            crate::note!("issue text (not sent): {}", crate::term::P(&file));
        }
        return Ok(());
    }
    if !yes {
        if !std::io::stdin().is_terminal() {
            anyhow::bail!("not a terminal: run `basal gemm-share --yes` to send without the question");
        }
        eprint!("send {} table(s)? [y/N] ", cands.len());
        std::io::stderr().flush()?;
        let mut answer = String::new();
        std::io::stdin().lock().read_line(&mut answer)?;
        if !matches!(answer.trim(), "y" | "Y" | "yes" | "tak" | "t") {
            crate::note!("nothing sent");
            return Ok(());
        }
    }
    let gh = gh_ready();
    for c in &cands {
        let text = body(&c.v, drv.as_deref())?;
        let file = c.path.with_extension("issue.md");
        std::fs::write(&file, &text).with_context(|| format!("writing {}", file.display()))?;
        if gh {
            let out = std::process::Command::new("gh")
                .args(["issue", "create", "--repo", REPO, "--label", LABEL, "--title", &title(&c.v), "--body-file"])
                .arg(&file)
                .output()
                .context("running gh")?;
            if out.status.success() {
                crate::done!("sent: {}", String::from_utf8_lossy(&out.stdout).trim());
                continue;
            }
            crate::warn!("gh issue create failed: {}", String::from_utf8_lossy(&out.stderr).trim());
        }
        crate::note!(
            "open https://github.com/{REPO}/issues/new?template=gemm-table.yml and paste {} (issue text with the \
             table)",
            crate::term::P(&file)
        );
    }
    Ok(())
}
